### ISSUE TITLE
InsertRow - Error when string property is null

### ISSUE THREAD

**Issue by simaoferreira24694** [spaf94/SFSQLiteApi#3]
Occurs error when we try to insert an object with a string property and the property value is null.

24-04-2019 09:52:17 | DEBUG | SFSQLiteApi.Utils.SQLiteQuery | ExecuteNonQuery | INSERT INTO Author(AuthorId,Name,BirthDate,ArrayA,ArrayB) VALUES('0',NULL,'01-01-0001 00:00:00','','')
24-04-2019 09:52:17 | ERROR | SFSQLiteApi.SFSQLiteConnection | InsertRow | constraint failed
NOT NULL constraint failed: Author.Name
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at SFSQLiteApi.Utils.SQLiteQuery.ExecuteNonQuery(String sqlQuery, SQLiteConnection connection) in C:\Work\dotnet-sf-sqlite\SFSQLiteApi\SFSQLiteApi\Utils\SQLiteQuery.cs:line 43
   at SFSQLiteApi.SFSQLiteConnection.InsertRow(Object obj) in C:\Work\dotnet-sf-sqlite\SFSQLiteApi\SFSQLiteApi\SFSQLiteConnection.cs:line 380

**Comment by simaoferreira24694** [comment]
Bug fixed (b8f071c94f155d3d4727c5e08774b36192e47e49).
